language: node_js
sudo: false
node_js:
  - stable
install:
  - npm install purescript pulp bower -g
  - bower install
script:
  - pulp build
after_success:
- >-
  test $TRAVIS_TAG &&
  echo $GITHUB_TOKEN | pulp login &&
  echo y | pulp publish --no-push
